tags:
  - name: Auth
    description: The authentication process always runs at the start of the application, before the permission and throttling checks occur
  - name: Hello
    description: Greetings API from TheCodeBUzz
path:
  /login:
    post:
      security:
        - bearerAuth: []
      tags:
        - Auth
      summary: Get greeting message from TheCodebuzz
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
      responses:
        200:
          # $ref: "#/components/responses/Success200"
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                  - message
                properties:
                  code:
                    type: number
                    description: HTTP reponse code
                    example: 200
                  message:
                    type: object
        400:
          $ref: "#/components/responses/BadRequest"

components:
  schemas:
    $ref: "swagger/schemas.yml"
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  requestBodies:
    BodyTemp:
      description: Property 'attrs' can have {} or [] format
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BodySchema"
  responses:
    Success200:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Success"
    Success201:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Success"
    Success204:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Success"
    BadRequest:
      description: 400 - Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: 401 - Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: 500 - Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    ServiceUnavailable:
      description: 503 - Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BodySuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Success"
